language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7

script:
  - cd module
  - sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: 
    - mguillermin@clever-age.com
    - nboire@clever-age.com
